# Generated by Django 2.1.4 on 2018-12-05 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util_request


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones_visita', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(blank=True, choices=[(1, 'Clientes'), (2, 'No Clientes')], null=True)),
                ('sub_tipo', models.IntegerField(blank=True, choices=[(1, 'Contrato Firmado'), (2, 'Versión de Prueba'), (3, 'Cuentan con Sistema'), (4, 'No Cuentan con Sistema')], null=True)),
                ('provincia', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=600, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_promotor', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_director', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_secretaria', models.CharField(blank=True, max_length=500, null=True)),
                ('contacto_extra', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(default=util_request.request_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actividades_colegio', to='colegios.Colegios'),
        ),
    ]
