# Generated by Django 2.1.4 on 2018-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegios',
            name='nombre_colegio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
